routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\GameController@index')->name('index');
Route::post('/rate', 'User\GameController@rate');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// for admin
Route::namespace('Admin')->name('admin.')->middleware(['auth', 'admin'])->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('ratings', 'RatingController@index')->name('rating.index');
    Route::get('ratings/import', 'RatingController@showFormImport')->name('rating.show.import');
    Route::post('ratings/import', 'RatingController@import')->name('rating.import');
    Route::get('testing', 'TestingController@index')->name('testing.index');
    Route::get('predictions', 'PredictionController@index')->name('prediction.index');

    Route::resource('games', GameController::class);
});

Route::get('similiarity', 'User\SimiliarityController@index');

app/Models/Prediction.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Prediction extends Model
{
    protected $fillable = ['user_id', 'game_id', 'prediction_score'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function game()
    {
        return $this->belongsTo(Game::class);
    }
}

app/Http/Controllers/Admin/PredictionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Prediction;
use Illuminate\Http\Request;

class PredictionController extends Controller
{
    public function index()
    {
        $predictions = Prediction::with(['user', 'game'])->get();

        return view('admin.prediction.index', compact('predictions'));
    }
}

resources/views/admin/prediction/index.blade.php
@extends('admin.shared.base')

@section('content')
    <!-- Button trigger modal -->
    <a class="btn btn-primary float-right" href="{{ route('admin.games.create') }}">
        Add New Game
    </a>

    <table class="table">
        <thead>
            <tr>
                <th>
                    No
                </th>
                <th>
                    User Name
                </th>
                <th>
                    Game
                </th>
                <th>
                    Score
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($predictions as $prediction)
                <tr>
                    <td>
                        {{ $loop->iteration }}
                    </td>
                    <td>
                        {{ $prediction->user->name }}
                    </td>
                    <td>
                        {{ $prediction->game->name }}
                    </td>
                    <td>
                        {{ $prediction->prediction_score }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <!-- Modal -->

@endsection