routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\GameController@index')->name('index');
Route::post('/rate', 'User\GameController@rate');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// for admin
Route::namespace('Admin')->name('admin.')->middleware(['auth', 'admin'])->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('ratings', 'RatingController@index')->name('rating.index');
    Route::get('ratings/import', 'RatingController@showFormImport')->name('rating.show.import');
    Route::post('ratings/import', 'RatingController@import')->name('rating.import');
    Route::get('testing', 'TestingController@index')->name('testing.index');
    Route::get('predictions', 'PredictionController@index')->name('prediction.index');

    Route::resource('games', GameController::class);
});

Route::get('similiarity', 'User\SimiliarityController@index');

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $fillable = ['name', 'genre', 'description', 'image'];

    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }
}

app/Http/Controllers/Admin/GameController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\GameRequest;
use App\Models\Game;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $games = Game::get();

        return view('admin.games.index', compact('games'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.games.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GameRequest $request)
    {
        $validated = $request->validated();

        $game = new Game($validated);
        $game->image = $request->hasFile('image')
            ? $this->uploadImage($request->file('image'))
            : null;
        $game->save();

        return redirect(route('admin.games.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        return view('admin.games.edit', compact('game'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GameRequest $request, Game $game)
    {
        $validated = $request->validated();

        $game->update($validated);
        $game->image = $request->hasFile('image')
            ? $this->uploadImage($request->file('image'))
            : ($game->image ?: null);
        $game->save();

        return redirect(route('admin.games.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Game $game)
    {
        $game->delete();

        return redirect()->back();
    }

    public function uploadImage($imageSource)
    {
        $imageName = Str::random(10) . '-' . time() . '.' . $imageSource->getClientOriginalExtension();

        Storage::disk('public')->putFileAs(
            'images',
            $imageSource,
            $imageName
        );

        return $imageName;
    }
}

app/Http/Controllers/User/GameController.php
<?php

namespace App\Http\Controllers\User;

use App\Events\Rated;
use App\Http\Controllers\Controller;
use App\Models\Game;
use App\Models\Prediction;
use App\Models\Rating;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GameController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $ratedGame = Rating::where('user_id', Auth::id())
            ->get()
            ->pluck('game_id')
            ->toArray();


        $predictionGames = Auth::user()->predictions;

        $games = Game::whereNotIn('id', $ratedGame)->get();

        return view('user.index', compact('games', 'predictionGames'));
    }

    public function rate(Request $request)
    {
        $this->validate($request, [
            'rating' => 'required|min:1',
            'id'     => 'required|exists:games'
        ]);

        $ratingExists = Rating::where('user_id', Auth::id())
            ->where('game_id', $request->id)
            ->exists();

        if ($ratingExists) {
            return response()->json([
                'message' => 'rating for this game already exists'
            ], 400);
        }

        Rating::create([
            'rating'  => $request->rating,
            'game_id' => $request->id,
            'user_id' => Auth::id()
        ]);

        event(new Rated($request->id));

        return response()->json([
            'success' => 'rate success'
        ], 200);
    }
}

resources/views/admin/games/create.blade.php
@extends('admin.shared.base')   

@section('content')
   <div class="card">
       <div class="card-body">
             <form action="{{route('admin.games.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="form-group">
                        <label for="name">
                            Name
                        </label>
                        <input type="text" class="form-control" name="name" id="name" value="{{old('name'?:'')}}">
                        @error('name')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="genre">
                            Genre
                        </label>
                        <input type="text" class="form-control" name="genre" id="genre" value="{{old('genre'?:'')}}">
                        @error('genre')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="description">
                            Description
                        </label>
                        <textarea class="form-control" name="description" id="description" cols="30" rows="10"></textarea>
                        @error('description')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="Image">
                            Image    
                        </label>
                        <input type="file" class="form-control" name="image" id="image">
                        @error('image')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
       </div>
   </div>
@endsection

resources/views/admin/games/edit.blade.php
@extends('admin.shared.base')

@section('content')
     <div class="card">
       <div class="card-body">
             <form action="{{route('admin.games.update', ['game'=>$game->id])}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="name">
                            Name
                        </label>
                        <input type="text" class="form-control" name="name" id="name" value="{{old('name')?:$game->name?:''}}">
                        @error('name')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="genre">
                            Genre
                        </label>
                        <input type="text" class="form-control" name="genre" id="genre" value="{{old('genre')?:$game->genre?:''}}">
                        @error('genre')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="description">
                            Description
                        </label>
                        <textarea class="form-control" name="description" id="description" cols="30" rows="10">{{old('description')?:$game->description?:''}}</textarea>
                        @error('description')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <img src="{{asset('images/'.$game->image)}}" alt="">
                        <label for="Image">
                            Image    
                        </label>
                        <input type="file" class="form-control" name="image" id="image">
                        @error('image')
                            <span class="small alert alert-danger">
                                {{$message}}
                            </span>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
       </div>
   </div>
@endsection

resources/views/admin/games/index.blade.php
@extends('admin.shared.base')

@section('content')
    <!-- Button trigger modal -->
    <a class="btn btn-primary float-right" href="{{route('admin.games.create')}}">
      Add New Game
    </a>

    <table class="table">
        <thead>
            <tr>
                <th>
                    No
                </th>
                <th>
                    Name
                </th>
                <th>
                    Image
                </th>
                <th>
                    Genre
                </th>
                <th>
                    Description
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($games as $game)
                <tr>
                    <td>
                        {{$loop->iteration}}
                    </td>
                    <td>
                        {{$game->name}}
                    </td>
                    <td>
                        <img style="width: 100px" src="{{asset('images/'.$game->image)}}" alt="" srcset="">
                    </td>
                    <td>
                        {{$game->genre}}
                    </td>
                    <td>
                        {{$game->description}}
                    </td>
                    <td>
                        <a class="btn tbn-sm btn-warning" href="{{route('admin.games.edit', ['game'=>$game->id])}}">
                            Edit
                        </a>
                        <form action="{{route('admin.games.destroy', ['game'=>$game->id])}}" method="POST" class="form-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn tbn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <!-- Modal -->
  
@endsection
 